### ISSUE TITLE
Enable Job for Terraform Provider Acceptance Tests 

### ISSUE THREAD

**Issue by kimdre** [germanbrew/terraform-provider-hetznerdns#11]
@jkroepke Should we enable the acceptenace tests now?

https://github.com/germanbrew/terraform-provider-hetznerdns/blob/aa4d0dd8f64f153a800fb3e5541bcbf061bc7a9d/.github/workflows/test.yaml#L62-L65

**Comment by jkroepke** [comment]
Do you have an working HETZNER_DNS_API_TOKEN to share?

**Comment by kimdre** [comment]
This directory is missing

https://github.com/germanbrew/terraform-provider-hetznerdns/blob/ff61109810ef89627fa1ccbb398bfb30bc4b8425/.github/workflows/test.yaml#L88

https://github.com/germanbrew/terraform-provider-hetznerdns/actions/runs/9235228260/job/25409804903?pr=14#step:6:8

**Comment by jkroepke** [comment]
Maybe makes more sense to migrate for new provider framework first, then take care of acc tests.
