### ISSUE TITLE
Consider allowing HETZNER_DNS_TOKEN as env var as well

### ISSUE THREAD

**Issue by flortsch** [germanbrew/terraform-provider-hetznerdns#110]
Hello!

I would like to make the suggestion to also allow the env var `HETZNER_DNS_TOKEN` for setting the Hetzner DNS API token.

We are using Terraform together with Ansible and its Hetzner DNS community module (https://docs.ansible.com/ansible/latest/collections/community/dns/docsite/hetzner_guide.html) that uses this env var for setting the token. By using the same env var, we would only need to configure the token once.

This would also align with the Hetzner Terraform provider (https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs) and the Ansible Hetzner Cloud inventory plugin (https://docs.ansible.com/ansible/latest/collections/hetzner/hcloud/hcloud_inventory.html) or parts of the Ansible Hetzner collection in general, which all use the same env var `HCLOUD_TOKEN` (note: without the `API`).

What do you think?

Edit: typos & formatting

**Comment by kimdre** [comment]
@jkroepke What do you say?
Should we implement this in addition to the existing `HETZNER_DNS_API_TOKEN`?

**Comment by jkroepke** [comment]
Feels like the env variable `HETZNER_DNS_TOKEN` is common sense, yes.

Another project is using that as well: https://github.com/arcanemachine/hetzner-dns-tools/blob/43f56659c06d990eb560897fa09191bdbca8ddf1/README.md

My recommendation would be to add support for `HETZNER_DNS_TOKEN` and add a deprecation note to the current one to keep the code clean. On next major version, we can remove the `HETZNER_DNS_API_TOKEN` env var.

**Comment by kimdre** [comment]
The next release will change to the `HETZNER_DNS_TOKEN` env var.
