### ISSUE TITLE
DOCS: Incorrect environment variable name (HETZNER_DNS_TOKEN)

### ISSUE THREAD

**Issue by hamidonos** [germanbrew/terraform-provider-hetznerdns#114]
The doc says `export HETZNER_DNS_TOKEN=<your api token>` which should make the api token available in the environment variables.

I get this error message

```
│ While configuring the client, the API token was not found in the
│ HETZNER_DNS_API_TOKEN environment variable or client configuration block
│ apitoken attribute.
```

Naming the variable `HETZNER_DNS_API_TOKEN` makes the plan work as expected.

## Notes

- I'm using OpenTofu

**Comment by kimdre** [comment]
Hi, we changed the token variable name with v3.2.0, are you using that version?
