### ISSUE TITLE
Zone resource does not allow dot separated TLD's (such as `co.za`)

### ISSUE THREAD

**Issue by J4NS-R** [germanbrew/terraform-provider-hetznerdns#117]
https://github.com/germanbrew/terraform-provider-hetznerdns/blob/5b7a37c4663b73dbec292eb8301e2ec4e5b0fbbf/internal/provider/zone_resource.go#L73

The regex for the `name` attribute of the zone resource only allows one dot character. There are top-level domains that contain two dot characters, such as `*.co.za`, `*.net.za` (my use cases), but also `.co.nz`, and many others. General members of the public have no control over the `co.za`, `co.nz` etc nameservers, and so there is no workaround here.

Please update the regex to allow two dot characters, or otherwise loosen the restrictions. Note that two-dot TLDs work fine with the upstream (timohirt/hetznerdns). 

Thank you for your consideration. Let me know if I should make a PR.

**Comment by J4NS-R** [comment]
@kimdre @jkroepke - bumping for visibility.

**Comment by kimdre** [comment]
You can try to

**Comment by J4NS-R** [comment]
Tested it now and it works!

@kimdre You are an absolute legend.
