### ISSUE TITLE
"API error: http status 429 unhandled" after migrating from timohirt/hetznerdns

### ISSUE THREAD

**Issue by ThomasLandauer** [germanbrew/terraform-provider-hetznerdns#146]
After following your migration guide at https://registry.terraform.io/providers/germanbrew/hetznerdns/latest/docs/guides/migration-from-timohirt-hetznerdns#migration-steps I'm getting this for every(?) resource:

> Error: API Error
> read record: http status 429 unhandled

`terraform plan` runs normally (i.e. endless lines in the console), then all these errors are showing up.

I even switched back to timohirt/hetznerdns to check if it's some temporary issue at Hetzner. But: Everything went fine there.

**Comment by kimdre** [comment]
Error 429 means you are probably getting rate limited or sent too many requests in a short amount of time.
Do you get the same error when you apply after waiting for a while?

**Comment by ThomasLandauer** [comment]
No, that's not the reason. I just tried it with your provider again => API error. Then switched back to timohirt => everything fine. Then switched back to yours again => API error. This all in less than 10 minutes. Besides, the "unhandled" in the error sounds like something unexpected.
I even commented out all hetznerdns resources, but that didn't change anything, since the resources still exist at Hetzner, and Terraform needs to refresh them anyway (I guess).
I do have some IDN domains (in punycode); and some long records written as required by timohirt. Could that be the cause?

**Comment by kimdre** [comment]
Could you please show me your provider config?

**Comment by ThomasLandauer** [comment]
Oh, it looks like it is a rate limiting issue, after all! I have several hundred resources, and it doesn't always stop at the same. Are you sending the requests differently than timohirt? With timohirt, there was always some sort of a pause, i.e. after many lines in the console, it stopped for a few seconds, then continued.

**Comment by kimdre** [comment]
Our provider is maybe more optimized and therefore faster but other than that there isn't that much difference. We changed the timeout behaviour though.

You can try to increase the `max_retries` provider setting: https://registry.terraform.io/providers/germanbrew/hetznerdns/latest/docs#max_retries-1

**Comment by ThomasLandauer** [comment]
Yeah, this indeed fixed it, but I had to go up all the way to `6`. So I'll close here, thanks!
Do you have a contact at Hetzner about this API? I'd like to ask them to increase the limit on their side...

**Comment by kimdre** [comment]
You can request an increase in the rate limit via ticket or e-mail to their support.
I will change the code so that rate limiting errors are handled correctly with a more useful message.

**Comment by kimdre** [comment]
For documentation: You can view the ratelimit usage in the terraform logs by running terraform plan or apply with `TF_LOG=DEBUG`.
E.g.: `TF_LOG=DEBUG terraform apply`

The http client will then log the entire http response to stdout including all headers. In the headers you will find rate limit details:

Header Name | Example Value
-- | --
x-ratelimit-remaining-minute | 296
x-ratelimit-limit-minute | 300
ratelimit-remaining | 296
ratelimit-limit | 300
ratelimit-reset | 50

**Comment by ThomasLandauer** [comment]
Good news: Hetzner indeed increased my limit :-) I asked them to adjust it automatically in the future with some rule like `10*(number of domains the user has)`

Bad news: `TF_LOG=DEBUG` is quite unusable: For every `Refreshing state` line I'm getting ~1 screen of `[DEBUG]` messages. And when I try to redirect it to some file (`TF_LOG=DEBUG terraform plan >> tflog.txt`), only the `Refreshing state` lines are saved there.  So I never see that ratelimit table :-(
Is there a way for you to move it to the very end of all output?
Or is there a way to change what's being written into `>> tflog.txt`?
