### ISSUE TITLE
Add handler for TXT records with more that 255 bytes length

### ISSUE THREAD

**Issue by kimdre** [germanbrew/terraform-provider-hetznerdns#20]
Strings in TXT records are by [design limited to 255 bytes](https://datatracker.ietf.org/doc/html/rfc4408#section-3.1.3). Strings with more characters get separated to double quoted substrings separated by space every 255 bytes/characters.

This causes the provider to always recreate ressources with strings that exceed this character limit.  The current workaround is to separate the string manually, as documented in our [Terraform provider docs](https://registry.terraform.io/providers/germanbrew/hetznerdns/3.0.0-beta.3/docs/resources/hetznerdns_record#txt-records--255-bytes).

**Comment by jkroepke** [comment]
ref https://github.com/timohirt/terraform-provider-hetznerdns/issues/54
