### ISSUE TITLE
Add provider function for IDN 

### ISSUE THREAD

**Issue by jkroepke** [germanbrew/terraform-provider-hetznerdns#21]
Ref: https://github.com/timohirt/terraform-provider-hetznerdns/issues/28

We should add an provider function to convert domains into punycode (IDN).

Provider functions are part of the framework (https://developer.hashicorp.com/terraform/plugin/framework/functions) and require terraform 1.8

**Comment by kimdre** [comment]
A simple example for this would be 

```go
package main

import (
	"fmt"

	"golang.org/x/net/idna"
)

var p *idna.Profile

func main() {
	p = idna.New()

	var url = "🍻über🔥.com"

	ascii, err := p.ToASCII(url)

	if err != nil {
		fmt.Println(err)
		return
	}

	unicode, err := p.ToUnicode(ascii)

	if err != nil {
		fmt.Println(err)
		return
	}

	fmt.Println(ascii)
	fmt.Println(unicode)
}
```

which will output

```
xn--ber-goa88194dfdc.com
🍻über🔥.com
```
