### ISSUE TITLE
Add provider options to set max retries

### ISSUE THREAD

**Issue by kimdre** [germanbrew/terraform-provider-hetznerdns#22]
Provide additional options to set `MaxRetries` and `RetryWaitMax` vars for http client.

https://github.com/germanbrew/terraform-provider-hetznerdns/blob/3624f9120ac2723fd72a149b4292f1b611a7e169/hetznerdns/api/client.go#L42

Related to https://github.com/timohirt/terraform-provider-hetznerdns/issues/59

**Comment by orefalo** [comment]
thank you
