### ISSUE TITLE
Generate provider GPG key

### ISSUE THREAD

**Issue by jkroepke** [germanbrew/terraform-provider-hetznerdns#3]
* Generate GPG Key for sign provider (https://developer.hashicorp.com/terraform/registry/providers/publishing#preparing-and-adding-a-signing-key)
* publish initial version without improvements (except release adjustments)
* publish provider on terraform registry
* publish gpg key on opentofu registry
* publish provider on opentofu registry

**Comment by kimdre** [comment]
GPG Key has been added as Org secrets `GPG_PRIVATE_KEY` and `PASSPHRASE`
