### ISSUE TITLE
Renaming apitoken api_token

### ISSUE THREAD

**Issue by jkroepke** [germanbrew/terraform-provider-hetznerdns#48]
Before we are release the v3, can we spell the provider setting correctly, e.g.: `api_token` instead `apitoken`

**Comment by jkroepke** [comment]
@kimdre your opinion?

**Comment by kimdre** [comment]
Perhaps we should provide an “alias” with a deprecation note for members of the old provider?

**Comment by jkroepke** [comment]
An major version may allow that without an deprecated note, but we can keep the ballast if we prefer.

The apitoken isn't part of the state, so we are good to go here

**Comment by kimdre** [comment]
Ok then lets just remove it :+1:
